export const ROOT_POP_SWIPE_CLOSE_THRESHOLD = 0.16;
export const ROOT_POP_SCALE_DELTA = 0.14;
export const ROOT_POP_FLICK_VELOCITY_THRESHOLD = 0.25;
export const ROOT_POP_MIN_FLICK_DISTANCE = 28;
export const ROOT_POP_COOLDOWN_MS = 450;
export const ROOT_POP_SWIPE_DURATION = 0.14;
export const ROOT_POP_BRIDGE_DURATION = 0.24;
export const ROOT_POP_FALLBACK_VIEWPORT_WIDTH = 400;